app.name: mesqueteltra
app.description: MQTT server demo

debug: true

spring.profiles.active: production
spring.application.name: ${app.name} (${spring.profiles.active})

server.context-path: /mesqueteltra
server.port: 9000
server.use-forward-headers: true
server.compression.enabled: true

#security.user.name: john_doe
#security.user.password: mysupersecretpassword

management.security.enabled: false
management.port: 9001
management.context-path: /manage

#spring.kafka.consumer.group-id: foo
#spring.kafka.consumer.auto-offset-reset: earliest

spring.redis:
  port: 18931

mesqueteltra.mqtt.server:
  port: 18881
  websocket-port: 18882
  client-name: mesqueteltra-client
  host: 0.0.0.0
  allow-anonymous: false
  ssl:
    port: 18883
    jks-path: 'keystore/example/example_keystore.jks'
    key-store-password: example
    key-manager-password: example

mesqueteltra.mqtt.client:
  enabled: true
  broker: ssl://localhost:18883
  #broker: tcp://localhost:18881
  #broker: ws://localhost:18882
  client-name: example-client
  user: example-user
  password: example
  ssl:
    jks-path: 'keystore/example/client_example_keystore.jks'
    key-store-password: example


mesqueteltra.mqtt.demo.clientA:
  enabled: true
  broker: ssl://localhost:18883
  #broker: tcp://localhost:18881
  #broker: ws://localhost:18882
  client-name: clientA
  user: userA
  password: example
  ssl:
    jks-path: 'keystore/example/client_example_keystore.jks'
    key-store-password: example

mesqueteltra.mqtt.demo.clientB:
  enabled: true
  broker: ssl://localhost:18893
  #broker: tcp://localhost:18881
  #broker: ws://localhost:18882
  client-name: clientB
  user: userB
  password: example
  ssl:
    jks-path: 'keystore/example/client_example_keystore.jks'
    key-store-password: example


mesqueteltra.ipfs:
  enabled: true
  multiaddr: '/ip4/127.0.0.1/tcp/5001'


mesqueteltra.redis:
  enabled: true
  port: ${spring.redis.port}

mesqueteltra.kafka:
  enabled: false