app.name: mesqueteltra
app.description: MQTT server demo

debug: true

spring.profiles.active: production
spring.application.name: ${app.name} (${spring.profiles.active})

server.context-path: /mesqueteltra
server.port: 9000
server.use-forward-headers: true
server.compression.enabled: true

#security.user.name: john_doe
#security.user.password: mysupersecretpassword

management.security.enabled: false
management.port: 9001
management.context-path: /manage

#spring.kafka.consumer.group-id: foo
#spring.kafka.consumer.auto-offset-reset: earliest

spring.redis:
  port: 18931

mesqueteltra.mqtt.server:
  port: 18831
  websocket-port: 18883
  client-name: mesqueteltra-client
  host: 0.0.0.0
  allow-anonymous: false

mesqueteltra.mqtt.client:
  enabled: true
  broker: tcp://localhost:18831
  client-name: mesqueteltra-client
  user: root
  password: public

mesqueteltra.ipfs:
  enabled: true
  multiaddr: '/ip4/127.0.0.1/tcp/5001'


mesqueteltra.redis:
  enabled: true
  port: ${spring.redis.port}

mesqueteltra.kafka:
  enabled: false